# -*- coding: utf-8 -*-
"""board2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18RcergL1zNfO2OvE9Ez_v3j1tU2EzerA
"""

list1 = ["-", "-", "-"]
list2 = ["-", "-", "-"]
list3 = ["-", "-", "-"]

print(list1)
print(list2)
print(list3)